/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AppAgendaRouteImport } from './routes/_app/agenda'
import { Route as AppAniversariosRouteImport } from './routes/_app/aniversarios'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppDiarioRouteImport } from './routes/_app/diario'
import { Route as AppExportarRouteImport } from './routes/_app/exportar'
import { Route as AppFilmesRouteImport } from './routes/_app/filmes'
import { Route as AppFinancasRouteImport } from './routes/_app/financas'
import { Route as AppHabitosRouteImport } from './routes/_app/habitos'
import { Route as AppListasRouteImport } from './routes/_app/listas'
import { Route as AppLivrosRouteImport } from './routes/_app/livros'
import { Route as AppMetasRouteImport } from './routes/_app/metas'
import { Route as AppSeriesRouteImport } from './routes/_app/series'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AppPodcastsIndexRouteImport } from './routes/_app/podcasts.index'
import { Route as AppPodcastsShowIdRouteImport } from './routes/_app/podcasts.$showId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppAniversariosRoute = AppAniversariosRouteImport.update({
  id: '/aniversarios',
  path: '/aniversarios',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDiarioRoute = AppDiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => AppRoute,
} as any)
const AppExportarRoute = AppExportarRouteImport.update({
  id: '/exportar',
  path: '/exportar',
  getParentRoute: () => AppRoute,
} as any)
const AppFilmesRoute = AppFilmesRouteImport.update({
  id: '/filmes',
  path: '/filmes',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancasRoute = AppFinancasRouteImport.update({
  id: '/financas',
  path: '/financas',
  getParentRoute: () => AppRoute,
} as any)
const AppHabitosRoute = AppHabitosRouteImport.update({
  id: '/habitos',
  path: '/habitos',
  getParentRoute: () => AppRoute,
} as any)
const AppListasRoute = AppListasRouteImport.update({
  id: '/listas',
  path: '/listas',
  getParentRoute: () => AppRoute,
} as any)
const AppLivrosRoute = AppLivrosRouteImport.update({
  id: '/livros',
  path: '/livros',
  getParentRoute: () => AppRoute,
} as any)
const AppMetasRoute = AppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppSeriesRoute = AppSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => AppRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppPodcastsIndexRoute = AppPodcastsIndexRouteImport.update({
  id: '/podcasts/',
  path: '/podcasts/',
  getParentRoute: () => AppRoute,
} as any)
const AppPodcastsShowIdRoute = AppPodcastsShowIdRouteImport.update({
  id: '/podcasts/$showId',
  path: '/podcasts/$showId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/agenda': typeof AppAgendaRoute
  '/aniversarios': typeof AppAniversariosRoute
  '/dashboard': typeof AppDashboardRoute
  '/diario': typeof AppDiarioRoute
  '/exportar': typeof AppExportarRoute
  '/filmes': typeof AppFilmesRoute
  '/financas': typeof AppFinancasRoute
  '/habitos': typeof AppHabitosRoute
  '/listas': typeof AppListasRoute
  '/livros': typeof AppLivrosRoute
  '/metas': typeof AppMetasRoute
  '/series': typeof AppSeriesRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/podcasts/$showId': typeof AppPodcastsShowIdRoute
  '/podcasts/': typeof AppPodcastsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/agenda': typeof AppAgendaRoute
  '/aniversarios': typeof AppAniversariosRoute
  '/dashboard': typeof AppDashboardRoute
  '/diario': typeof AppDiarioRoute
  '/exportar': typeof AppExportarRoute
  '/filmes': typeof AppFilmesRoute
  '/financas': typeof AppFinancasRoute
  '/habitos': typeof AppHabitosRoute
  '/listas': typeof AppListasRoute
  '/livros': typeof AppLivrosRoute
  '/metas': typeof AppMetasRoute
  '/series': typeof AppSeriesRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/podcasts/$showId': typeof AppPodcastsShowIdRoute
  '/podcasts': typeof AppPodcastsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/aniversarios': typeof AppAniversariosRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/diario': typeof AppDiarioRoute
  '/_app/exportar': typeof AppExportarRoute
  '/_app/filmes': typeof AppFilmesRoute
  '/_app/financas': typeof AppFinancasRoute
  '/_app/habitos': typeof AppHabitosRoute
  '/_app/listas': typeof AppListasRoute
  '/_app/livros': typeof AppLivrosRoute
  '/_app/metas': typeof AppMetasRoute
  '/_app/series': typeof AppSeriesRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_app/podcasts/$showId': typeof AppPodcastsShowIdRoute
  '/_app/podcasts/': typeof AppPodcastsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/agenda'
    | '/aniversarios'
    | '/dashboard'
    | '/diario'
    | '/exportar'
    | '/filmes'
    | '/financas'
    | '/habitos'
    | '/listas'
    | '/livros'
    | '/metas'
    | '/series'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/podcasts/$showId'
    | '/podcasts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/agenda'
    | '/aniversarios'
    | '/dashboard'
    | '/diario'
    | '/exportar'
    | '/filmes'
    | '/financas'
    | '/habitos'
    | '/listas'
    | '/livros'
    | '/metas'
    | '/series'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/podcasts/$showId'
    | '/podcasts'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_app/agenda'
    | '/_app/aniversarios'
    | '/_app/dashboard'
    | '/_app/diario'
    | '/_app/exportar'
    | '/_app/filmes'
    | '/_app/financas'
    | '/_app/habitos'
    | '/_app/listas'
    | '/_app/livros'
    | '/_app/metas'
    | '/_app/series'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_app/podcasts/$showId'
    | '/_app/podcasts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aniversarios': {
      id: '/_app/aniversarios'
      path: '/aniversarios'
      fullPath: '/aniversarios'
      preLoaderRoute: typeof AppAniversariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/diario': {
      id: '/_app/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof AppDiarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exportar': {
      id: '/_app/exportar'
      path: '/exportar'
      fullPath: '/exportar'
      preLoaderRoute: typeof AppExportarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/filmes': {
      id: '/_app/filmes'
      path: '/filmes'
      fullPath: '/filmes'
      preLoaderRoute: typeof AppFilmesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financas': {
      id: '/_app/financas'
      path: '/financas'
      fullPath: '/financas'
      preLoaderRoute: typeof AppFinancasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/habitos': {
      id: '/_app/habitos'
      path: '/habitos'
      fullPath: '/habitos'
      preLoaderRoute: typeof AppHabitosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/listas': {
      id: '/_app/listas'
      path: '/listas'
      fullPath: '/listas'
      preLoaderRoute: typeof AppListasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/livros': {
      id: '/_app/livros'
      path: '/livros'
      fullPath: '/livros'
      preLoaderRoute: typeof AppLivrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metas': {
      id: '/_app/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AppMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/series': {
      id: '/_app/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof AppSeriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/podcasts/': {
      id: '/_app/podcasts/'
      path: '/podcasts'
      fullPath: '/podcasts/'
      preLoaderRoute: typeof AppPodcastsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/podcasts/$showId': {
      id: '/_app/podcasts/$showId'
      path: '/podcasts/$showId'
      fullPath: '/podcasts/$showId'
      preLoaderRoute: typeof AppPodcastsShowIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppAniversariosRoute: typeof AppAniversariosRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDiarioRoute: typeof AppDiarioRoute
  AppExportarRoute: typeof AppExportarRoute
  AppFilmesRoute: typeof AppFilmesRoute
  AppFinancasRoute: typeof AppFinancasRoute
  AppHabitosRoute: typeof AppHabitosRoute
  AppListasRoute: typeof AppListasRoute
  AppLivrosRoute: typeof AppLivrosRoute
  AppMetasRoute: typeof AppMetasRoute
  AppSeriesRoute: typeof AppSeriesRoute
  AppPodcastsShowIdRoute: typeof AppPodcastsShowIdRoute
  AppPodcastsIndexRoute: typeof AppPodcastsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppAniversariosRoute: AppAniversariosRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDiarioRoute: AppDiarioRoute,
  AppExportarRoute: AppExportarRoute,
  AppFilmesRoute: AppFilmesRoute,
  AppFinancasRoute: AppFinancasRoute,
  AppHabitosRoute: AppHabitosRoute,
  AppListasRoute: AppListasRoute,
  AppLivrosRoute: AppLivrosRoute,
  AppMetasRoute: AppMetasRoute,
  AppSeriesRoute: AppSeriesRoute,
  AppPodcastsShowIdRoute: AppPodcastsShowIdRoute,
  AppPodcastsIndexRoute: AppPodcastsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
